import { useState } from "react";
import { copyResults as copyToClipboard } from "../../utils/copyResults";
import CalculatorActions from "../common/CalculatorActions";
import CalculatorHeader from "../common/CalculatorHeader";
import CalculatorSection from "../common/CalculatorSection";
import CalculatorShell from "../common/CalculatorShell";
import CalculatorSummary from "../common/CalculatorSummary";
import InlineMessage from "../common/InlineMessage";
import LoadingOverlay from "../common/LoadingOverlay";
import ResultCard from "../common/ResultCard";
import ToolDisclaimer from "../common/ToolDisclaimer";

const currencies = [
  { code: "JMD", name: "Jamaican Dollar" },
  { code: "USD", name: "US Dollar" },
  { code: "CAD", name: "Canadian Dollar" },
  { code: "GBP", name: "British Pound" },
  { code: "EUR", name: "Euro" },
  { code: "KYD", name: "Cayman Islands Dollar" },
  { code: "TTD", name: "Trinidad and Tobago Dollar" },
  { code: "BBD", name: "Barbadian Dollar" },
  { code: "XCD", name: "East Caribbean Dollar" },
  { code: "BSD", name: "Bahamian Dollar" },
];

const formatCurrency = (value, currency) =>
  new Intl.NumberFormat("en-JM", {
    style: "currency",
    currency,
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  }).format(value);

const formatRate = (value) =>
  new Intl.NumberFormat("en-JM", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 6,
  }).format(value);

function CurrencyConverter() {
  const [amount, setAmount] = useState("");
  const [fromCurrency, setFromCurrency] = useState("USD");
  const [toCurrency, setToCurrency] = useState("JMD");
  const [error, setError] = useState("");
  const [message, setMessage] = useState("");
  const [result, setResult] = useState(null);
  const [isLoading, setIsLoading] = useState(false);

  const clearResults = () => {
    setResult(null);
    setError("");
    setMessage("");
  };

  const resetConverter = () => {
    setAmount("");
    setFromCurrency("USD");
    setToCurrency("JMD");
    clearResults();
  };

  const swapCurrencies = () => {
    setFromCurrency(toCurrency);
    setToCurrency(fromCurrency);
    clearResults();
  };

  const convertCurrency = async () => {
    const enteredAmount = Number.parseFloat(amount);

    if (!Number.isFinite(enteredAmount) || enteredAmount <= 0) {
      clearResults();
      setError("Please enter a valid amount greater than zero.");
      return;
    }

    if (enteredAmount > 1000000000) {
      clearResults();
      setError("Please enter a realistic amount.");
      return;
    }

    setError("");
    setMessage("");
    setIsLoading(true);

    try {
      if (fromCurrency === toCurrency) {
        setResult({
          originalAmount: enteredAmount,
          convertedAmount: enteredAmount,
          rate: 1,
          inverseRate: 1,
          fromCurrency,
          toCurrency,
          rateDate: "Same currency",
        });

        return;
      }

      const response = await fetch(
        `https://api.frankfurter.dev/v2/rate/${fromCurrency}/${toCurrency}`,
      );

      if (!response.ok) {
        throw new Error("Exchange-rate request failed.");
      }

      const data = await response.json();
      const rate = Number(data.rate);

      if (!Number.isFinite(rate) || rate <= 0) {
        throw new Error("A valid exchange rate was not returned.");
      }

      setResult({
        originalAmount: enteredAmount,
        convertedAmount: enteredAmount * rate,
        rate,
        inverseRate: 1 / rate,
        fromCurrency,
        toCurrency,
        rateDate: data.date || "Latest available",
      });
    } catch {
      setResult(null);
      setError(
        "We could not retrieve the exchange rate. Please check your connection and try again.",
      );
    } finally {
      setIsLoading(false);
    }
  };

  const handleCopyResults = async () => {
    if (!result) return;

    const text = `
JamaicaTools Currency Conversion

${formatCurrency(result.originalAmount, result.fromCurrency)}
=
${formatCurrency(result.convertedAmount, result.toCurrency)}

1 ${result.fromCurrency} = ${formatRate(result.rate)} ${result.toCurrency}
1 ${result.toCurrency} = ${formatRate(result.inverseRate)} ${result.fromCurrency}

Rate date: ${result.rateDate}
Generated by JamaicaTools
`;

    await copyToClipboard(text, setMessage);
  };

  return (
    <CalculatorShell title="Currency Converter">
      <CalculatorHeader
        title="💱 Currency Exchange Calculator"
        subtitle="Convert Jamaican Dollars and major international currencies."
      />

      <form
        noValidate
        onSubmit={(event) => {
          event.preventDefault();

          if (!isLoading) {
            convertCurrency();
          }
        }}
      >
        <div className="grid gap-6 md:grid-cols-2">
          <div className="md:col-span-2">
            <label className="mb-2 block font-semibold" htmlFor="currency-amount">
              Amount
            </label>

            <input
              id="currency-amount"
              type="number"
              min="0.01"
              step="0.01"
              value={amount}
              onChange={(event) => {
                setAmount(event.target.value);
                clearResults();
              }}
              placeholder="Example: 100"
              className="h-14 w-full rounded-xl border px-4"
            />

            <p className="mt-2 text-xs text-slate-500">
              Enter the amount you want to convert.
            </p>
          </div>

          <div>
            <label className="mb-2 block font-semibold" htmlFor="from-currency">
              From Currency
            </label>

            <select
              id="from-currency"
              value={fromCurrency}
              onChange={(event) => {
                setFromCurrency(event.target.value);
                clearResults();
              }}
              className="h-14 w-full rounded-xl border px-4"
            >
              {currencies.map((currency) => (
                <option key={currency.code} value={currency.code}>
                  {currency.code} — {currency.name}
                </option>
              ))}
            </select>
          </div>

          <div>
            <label className="mb-2 block font-semibold" htmlFor="to-currency">
              To Currency
            </label>

            <select
              id="to-currency"
              value={toCurrency}
              onChange={(event) => {
                setToCurrency(event.target.value);
                clearResults();
              }}
              className="h-14 w-full rounded-xl border px-4"
            >
              {currencies.map((currency) => (
                <option key={currency.code} value={currency.code}>
                  {currency.code} — {currency.name}
                </option>
              ))}
            </select>
          </div>
        </div>

        <button
          type="button"
          onClick={swapCurrencies}
          className="mt-5 w-full rounded-xl border border-green-200 bg-green-50 px-5 py-3 font-semibold text-green-700 transition hover:bg-green-100"
        >
          ⇄ Swap {fromCurrency} and {toCurrency}
        </button>

        <CalculatorActions
          onReset={resetConverter}
          onCopy={handleCopyResults}
          disableCopy={!result}
          calculateLabel={isLoading ? "Converting..." : "Convert Currency"}
          calculateType="submit"
          isCopied={Boolean(message)}
        />
      </form>

      <LoadingOverlay
        show={isLoading}
        text="Fetching the latest exchange rate..."
      />

      {error && <InlineMessage type="error">{error}</InlineMessage>}

      {message && (
        <InlineMessage type="success">
          {message}
        </InlineMessage>
      )}

      {result && (
        <>
          <div className="mt-10 grid gap-4 xl:grid-cols-3">
            <ResultCard
              label={`${result.fromCurrency} Amount`}
              value={formatCurrency(
                result.originalAmount,
                result.fromCurrency,
              )}
              helper="Original amount"
              color="blue"
            />

            <ResultCard
              label={`${result.toCurrency} Amount`}
              value={formatCurrency(
                result.convertedAmount,
                result.toCurrency,
              )}
              helper="Converted amount"
              color="green"
            />

            <ResultCard
              label="Exchange Rate"
              value={formatRate(result.rate)}
              helper={`1 ${result.fromCurrency} in ${result.toCurrency}`}
              color="orange"
            />
          </div>

          <CalculatorSummary
            title="Conversion Summary"
            items={[
              {
                label: "Original Amount",
                value: formatCurrency(
                  result.originalAmount,
                  result.fromCurrency,
                ),
                color: "text-slate-900",
              },
              {
                label: "Converted Amount",
                value: formatCurrency(
                  result.convertedAmount,
                  result.toCurrency,
                ),
                color: "text-green-700",
              },
              {
                label: `1 ${result.fromCurrency}`,
                value: `${formatRate(result.rate)} ${result.toCurrency}`,
                color: "text-blue-700",
              },
              {
                label: `1 ${result.toCurrency}`,
                value: `${formatRate(result.inverseRate)} ${result.fromCurrency}`,
              },
              {
                label: "Rate Date",
                value: result.rateDate,
              },
            ]}
          />

          <CalculatorSection title="Rate Information" tone="blue">
            <p className="text-sm leading-6 text-slate-700">
              Exchange rates can differ between banks, cambios, credit-card
              companies and money-transfer services. Fees and buying or selling
              margins are not included in this conversion.
            </p>
          </CalculatorSection>
        </>
      )}

      <ToolDisclaimer>
        Currency conversions are estimates based on the latest available
        reference rate. Your bank, cambio, card provider or transfer service may
        apply a different rate and additional fees.
      </ToolDisclaimer>
    </CalculatorShell>
  );
}

export default CurrencyConverter;
