import { useState } from "react";
import { formatCurrency } from "../../utils/formatCurrency";
import { copyResults as copyToClipboard } from "../../utils/copyResults";


function SalaryCalculator() {
  const [grossSalary, setGrossSalary] = useState("");
  const [period, setPeriod] = useState("monthly");
  const [error, setError] = useState("");
  const [message, setMessage] = useState("");
  const [result, setResult] = useState(null);

  
const clearResults = () => {
  setResult(null);
  setError("");
  setMessage("");
};

const handleCopyResults = async () => {
  if (!result) return;

  const text = `
Jamaica Salary Calculation

Gross Salary: ${formatCurrency(result.gross)}
Net Salary: ${formatCurrency(result.netPay)}
PAYE: ${formatCurrency(result.paye)}
NIS: ${formatCurrency(result.nis)}
NHT: ${formatCurrency(result.nht)}
Education Tax: ${formatCurrency(result.educationTax)}
Total Deductions: ${formatCurrency(result.totalDeductions)}

Generated by JamaicaTools
`;

  await copyToClipboard(text, setMessage);
};

  const resetCalculator = () => {
    setGrossSalary("");
    setPeriod("monthly");
    clearResults();
  };


  const calculateSalary = () => {
    const salary = parseFloat(grossSalary);


  if (isNaN(salary) || salary <= 0) {
  clearResults();
  setError("Please enter a valid gross salary.");
  return;
}

if (salary > 100000000) {
  clearResults();
  setError("Please enter a realistic salary amount.");
  return;
}

    const annualSalary =
      period === "monthly"
        ? salary * 12
        : period === "fortnightly"
        ? salary * 26
        : period === "weekly"
        ? salary * 52
        : salary;

    const annualThreshold = 1876614;
    const annualNisCap = 5000000;

    const nisAnnual = Math.min(annualSalary, annualNisCap) * 0.03;
    const nhtAnnual = annualSalary * 0.02;
    const educationTaxAnnual = (annualSalary - nisAnnual) * 0.0225;

    const taxableIncome = Math.max(annualSalary - annualThreshold, 0);
    const payeAnnual =
      taxableIncome <= 6000000
        ? taxableIncome * 0.25
        : 6000000 * 0.25 + (taxableIncome - 6000000) * 0.3;

    const totalDeductionsAnnual =
      nisAnnual + nhtAnnual + educationTaxAnnual + payeAnnual;

    const netAnnual = annualSalary - totalDeductionsAnnual;

    const divisor =
      period === "monthly"
        ? 12
        : period === "fortnightly"
        ? 26
        : period === "weekly"
        ? 52
        : 1;

    setError("");
setMessage("");

setResult({
      gross: annualSalary / divisor,
      paye: payeAnnual / divisor,
      nis: nisAnnual / divisor,
      nht: nhtAnnual / divisor,
      educationTax: educationTaxAnnual / divisor,
      totalDeductions: totalDeductionsAnnual / divisor,
      netPay: netAnnual / divisor,
    });
  };

  return (
    <div className="w-full max-w-full overflow-hidden rounded-3xl border border-slate-200 bg-white p-6 shadow-lg">
      <h2 className="mb-8 text-2xl font-bold">Jamaica Salary Calculator</h2>

      <div className="mb-8 rounded-xl border border-green-200 bg-green-50 p-4">
        <p className="font-semibold text-green-700">
          🇯🇲 Jamaica Payroll Calculator
        </p>
        <p className="mt-1 text-sm text-slate-600">
          Based on the current 2026 Jamaican payroll tax rules.
        </p>
      </div>

      <div className="grid gap-6 md:grid-cols-2">
        <div>
          <label className="mb-2 block font-semibold">Gross Salary</label>
          <input
  type="number"
  min="1"
  step="1000"
  value={grossSalary}
  onChange={(e) => {
    setGrossSalary(e.target.value);
    clearResults();
  }}
  
  onKeyDown={(e) => {
    if (e.key === "Enter") {
      calculateSalary();
    }
  }}
  placeholder="Example: 150000"
  className="h-14 w-full rounded-xl border px-4"
/>
          <p className="mt-2 text-xs text-slate-500">
            Enter salary before deductions.
          </p>
        </div>

        <div>
          <label className="mb-2 block font-semibold">Salary Period</label>
          <select
            value={period}
            onChange={(e) => {
              setPeriod(e.target.value);
              clearResults();
            }}
            className="h-14 w-full rounded-xl border px-4"
          >
            <option value="monthly">Monthly</option>
            <option value="fortnightly">Fortnightly</option>
            <option value="weekly">Weekly</option>
            <option value="annual">Annual</option>
          </select>
          <p className="mt-2 text-xs text-slate-500">
            Choose how your salary is paid.
          </p>
        </div>
      </div>

      <div className="mt-8 flex flex-wrap gap-4">
        <button
          onClick={calculateSalary}
          className="h-14 flex-1 rounded-xl bg-green-700 px-8 font-semibold text-white hover:bg-green-800"
        >
          Calculate Take-Home Pay
        </button>

        <button
          onClick={resetCalculator}
          className="h-14 rounded-xl border border-slate-300 px-8 font-semibold text-slate-700 hover:border-green-700 hover:text-green-700"
        >
          Reset
        </button>

        <button
  onClick={handleCopyResults}
  disabled={!result}
  className={`h-14 rounded-xl px-8 font-semibold transition-all duration-300
    ${
      message
        ? "border border-green-600 bg-green-600 text-white"
        : "border border-blue-300 text-blue-700 hover:bg-blue-50"
    }
    disabled:cursor-not-allowed disabled:opacity-40`}
>
  {message ? "✅ Copied!" : "📋 Copy Results"}
</button>
      </div>

    
      {error && (
        <div className="mt-6 rounded-xl border border-red-200 bg-red-50 px-5 py-4 text-sm font-medium text-red-700">
          {error}
        </div>
      )}

      {result && (
        <>
          <div className="mt-10 grid gap-4 xl:grid-cols-3">
            <div className="min-w-0 rounded-xl bg-green-50 p-6">
              <p className="text-sm text-slate-500">💵 Estimated Net Pay</p>
              <h3 className="mt-2 break-words text-lg font-bold text-green-700 sm:text-xl">
                {formatCurrency(result.netPay)}
              </h3>
              <p className="mt-2 text-sm text-slate-500">After deductions</p>
            </div>

            <div className="min-w-0 rounded-xl bg-blue-50 p-6">
              <p className="text-sm text-slate-500">📊 Total Deductions</p>
              <h3 className="mt-2 break-words text-lg font-bold text-blue-700 sm:text-xl">
                {formatCurrency(result.totalDeductions)}
              </h3>
              <p className="mt-2 text-sm text-slate-500">PAYE, NIS, NHT, tax</p>
            </div>

            <div className="min-w-0 rounded-xl bg-orange-50 p-6">
              <p className="text-sm text-slate-500">🏦 Gross Pay</p>
              <h3 className="mt-2 break-words text-lg font-bold text-orange-700 sm:text-xl">

                {formatCurrency(result.gross)}
              </h3>
              <p className="mt-2 text-sm text-slate-500">Before deductions</p>
            </div>
          </div>

          {message && (
  <div
    className="
      mt-6
      flex
      items-center
      gap-3
      rounded-xl
      border
      border-green-200
      bg-green-50
      p-4
      text-green-700
      font-medium
      animate-fade-in
    "
  >
    <span className="text-xl">✅</span>
    <span>{message}</span>
  </div>
)}

          <div className="mt-8 rounded-2xl border border-slate-200 bg-slate-50 p-6">
            <h3 className="text-xl font-bold text-slate-900">
              Payroll Summary
            </h3>

            <div className="mt-5 divide-y divide-slate-200">
              {[
                ["💰 Gross Pay", result.gross, "text-slate-900"],
                ["🧾 PAYE", result.paye, "text-red-700"],
                ["🛡️ NIS", result.nis, "text-indigo-700"],
                ["🏠 NHT", result.nht, "text-purple-700"],
                ["🎓 Education Tax", result.educationTax, "text-amber-700"],
                ["Total Deductions", result.totalDeductions, "text-blue-700"],
                ["Estimated Net Pay", result.netPay, "text-green-700"],
              ].map(([label, value, color]) => (
                <div key={label} className="flex justify-between py-3">
                  <span className={`font-semibold ${color}`}>{label}</span>
                  <strong>{formatCurrency(value)}</strong>
                </div>
              ))}
            </div>
          </div>

          <p className="mt-1 text-sm text-slate-500">
  Calculated {new Date().toLocaleString()}
</p>

          <div className="mt-8 rounded-2xl border border-green-100 bg-white p-6">
            <h3 className="text-xl font-bold text-slate-900">
              Estimated Payslip
            </h3>

            <div className="mt-5 divide-y divide-slate-200">
              {[
                ["Gross Pay", result.gross],
                ["PAYE", result.paye],
                ["NIS", result.nis],
                ["NHT", result.nht],
                ["Education Tax", result.educationTax],
              ].map(([label, value]) => (
                <div key={label} className="flex justify-between py-2">
                  <span>{label}</span>
                  <strong>{formatCurrency(value)}</strong>
                </div>
              ))}

              <div className="flex justify-between py-2 font-bold text-green-700">
                <span>Take Home Pay</span>
                <span>{formatCurrency(result.netPay)}</span>
              </div>
            </div>
          </div>

          <div className="mt-8 rounded-xl border border-blue-200 bg-blue-50 p-5">
            <h3 className="font-bold text-blue-800">💡 Did You Know?</h3>
            <p className="mt-2 text-sm text-slate-700">
              PAYE is only charged after Jamaica&apos;s annual tax-free
              threshold. NIS contributions are capped annually, while NHT and
              Education Tax are generally calculated as a percentage of your
              earnings.
            </p>
          </div>
        </>
      )}
      
      
      <div className="mt-8 rounded-xl bg-slate-100 p-4 text-sm text-slate-600">
        <strong>Disclaimer:</strong> This calculator provides an estimate only.
        Payroll deductions may vary based on official tax updates, pension,
        benefits, exemptions, and employer payroll settings.
      </div>
    </div>
  );
}

export default SalaryCalculator;