import { useState } from "react";
import { formatCurrency } from "../../utils/formatCurrency";
import { copyResults as copyToClipboard } from "../../utils/copyResults";
import ResultCard from "../common/ResultCard";
import CalculatorShell from "../common/CalculatorShell";
import CalculatorHeader from "../common/CalculatorHeader";
import CalculatorSummary from "../common/CalculatorSummary";
import CalculatorActions from "../common/CalculatorActions";
import ToolDisclaimer from "../common/ToolDisclaimer";


function SalaryCalculator() {
  const [grossSalary, setGrossSalary] = useState("");
  const [period, setPeriod] = useState("monthly");
  const [error, setError] = useState("");
  const [message, setMessage] = useState("");
  const [result, setResult] = useState(null);

  
const clearResults = () => {
  setResult(null);
  setError("");
  setMessage("");
};

const handleCopyResults = async () => {
  if (!result) return;

  const text = `
Jamaica Salary Calculation

Gross Salary: ${formatCurrency(result.gross)}
Net Salary: ${formatCurrency(result.netPay)}
PAYE: ${formatCurrency(result.paye)}
NIS: ${formatCurrency(result.nis)}
NHT: ${formatCurrency(result.nht)}
Education Tax: ${formatCurrency(result.educationTax)}
Total Deductions: ${formatCurrency(result.totalDeductions)}

Generated by JamaicaTools
`;

  await copyToClipboard(text, setMessage);
};

  const resetCalculator = () => {
    setGrossSalary("");
    setPeriod("monthly");
    clearResults();
  };


  const calculateSalary = () => {
    const salary = parseFloat(grossSalary);


  if (isNaN(salary) || salary <= 0) {
  clearResults();
  setError("Please enter a valid gross salary.");
  return;
}

if (salary > 100000000) {
  clearResults();
  setError("Please enter a realistic salary amount.");
  return;
}

    const annualSalary =
      period === "monthly"
        ? salary * 12
        : period === "fortnightly"
        ? salary * 26
        : period === "weekly"
        ? salary * 52
        : salary;

    const annualThreshold = 1876614;
    const annualNisCap = 5000000;

    const nisAnnual = Math.min(annualSalary, annualNisCap) * 0.03;
    const nhtAnnual = annualSalary * 0.02;
    const educationTaxAnnual = (annualSalary - nisAnnual) * 0.0225;

    const taxableIncome = Math.max(annualSalary - annualThreshold, 0);
    const payeAnnual =
      taxableIncome <= 6000000
        ? taxableIncome * 0.25
        : 6000000 * 0.25 + (taxableIncome - 6000000) * 0.3;

    const totalDeductionsAnnual =
      nisAnnual + nhtAnnual + educationTaxAnnual + payeAnnual;

    const netAnnual = annualSalary - totalDeductionsAnnual;

    const divisor =
      period === "monthly"
        ? 12
        : period === "fortnightly"
        ? 26
        : period === "weekly"
        ? 52
        : 1;

    setError("");
setMessage("");

setResult({
      gross: annualSalary / divisor,
      paye: payeAnnual / divisor,
      nis: nisAnnual / divisor,
      nht: nhtAnnual / divisor,
      educationTax: educationTaxAnnual / divisor,
      totalDeductions: totalDeductionsAnnual / divisor,
      netPay: netAnnual / divisor,
    });
  };

  return (
  <CalculatorShell title="Jamaica Salary Calculator">

      <CalculatorHeader
  title="🇯🇲 Jamaica Payroll Calculator"
  subtitle="Based on the current 2026 Jamaican payroll tax rules."
/>

      <div className="grid gap-6 md:grid-cols-2">
        <div>
          <label className="mb-2 block font-semibold">Gross Salary</label>
          <input
  type="number"
  min="1"
  step="1000"
  value={grossSalary}
  onChange={(e) => {
    setGrossSalary(e.target.value);
    clearResults();
  }}
  
  onKeyDown={(e) => {
    if (e.key === "Enter") {
      calculateSalary();
    }
  }}
  placeholder="Example: 150000"
  className="h-14 w-full rounded-xl border px-4"
/>
          <p className="mt-2 text-xs text-slate-500">
            Enter salary before deductions.
          </p>
        </div>

        <div>
          <label className="mb-2 block font-semibold">Salary Period</label>
          <select
            value={period}
            onChange={(e) => {
              setPeriod(e.target.value);
              clearResults();
            }}
            className="h-14 w-full rounded-xl border px-4"
          >
            <option value="monthly">Monthly</option>
            <option value="fortnightly">Fortnightly</option>
            <option value="weekly">Weekly</option>
            <option value="annual">Annual</option>
          </select>
          <p className="mt-2 text-xs text-slate-500">
            Choose how your salary is paid.
          </p>
        </div>
      </div>
<CalculatorActions
  onCalculate={calculateSalary}
  onReset={resetCalculator}
  onCopy={handleCopyResults}
  disableCopy={!result}
  calculateLabel="Calculate Take-Home Pay"
  isCopied={Boolean(message)}
/>

    
      {error && (
        <div className="mt-6 rounded-xl border border-red-200 bg-red-50 px-5 py-4 text-sm font-medium text-red-700">
          {error}
        </div>
      )}

      {result && (
        <>
          <div className="mt-10 grid gap-4 xl:grid-cols-3">
  <ResultCard
    label="💵 Estimated Net Pay"
    value={formatCurrency(result.netPay)}
    helper="After deductions"
    color="green"
  />

  <ResultCard
    label="📊 Total Deductions"
    value={formatCurrency(result.totalDeductions)}
    helper="PAYE, NIS, NHT, tax"
    color="blue"
  />

  <ResultCard
    label="🏦 Gross Pay"
    value={formatCurrency(result.gross)}
    helper="Before deductions"
    color="orange"
  />
</div>

          {message && (
  <div
    className="
      mt-6
      flex
      items-center
      gap-3
      rounded-xl
      border
      border-green-200
      bg-green-50
      p-4
      text-green-700
      font-medium
      animate-fade-in
    "
  >
    <span className="text-xl">✅</span>
    <span>{message}</span>
  </div>
)}

          <CalculatorSummary
  title="Payroll Summary"
  items={[
    {
      label: "💰 Gross Pay",
      value: formatCurrency(result.gross),
      color: "text-slate-900",
    },
    {
      label: "🧾 PAYE",
      value: formatCurrency(result.paye),
      color: "text-red-700",
    },
    {
      label: "🛡️ NIS",
      value: formatCurrency(result.nis),
      color: "text-indigo-700",
    },
    {
      label: "🏠 NHT",
      value: formatCurrency(result.nht),
      color: "text-purple-700",
    },
    {
      label: "🎓 Education Tax",
      value: formatCurrency(result.educationTax),
      color: "text-amber-700",
    },
    {
      label: "Total Deductions",
      value: formatCurrency(result.totalDeductions),
      color: "text-blue-700",
    },
    {
      label: "Estimated Net Pay",
      value: formatCurrency(result.netPay),
      color: "text-green-700",
    },
  ]}
/>

          <p className="mt-1 text-sm text-slate-500">
  Calculated {new Date().toLocaleString()}
</p>

          <div className="mt-8 rounded-2xl border border-green-100 bg-white p-6">
            <h3 className="text-xl font-bold text-slate-900">
              Estimated Payslip
            </h3>

            <div className="mt-5 divide-y divide-slate-200">
              {[
                ["Gross Pay", result.gross],
                ["PAYE", result.paye],
                ["NIS", result.nis],
                ["NHT", result.nht],
                ["Education Tax", result.educationTax],
              ].map(([label, value]) => (
                <div key={label} className="flex justify-between py-2">
                  <span>{label}</span>
                  <strong>{formatCurrency(value)}</strong>
                </div>
              ))}

              <div className="flex justify-between py-2 font-bold text-green-700">
                <span>Take Home Pay</span>
                <span>{formatCurrency(result.netPay)}</span>
              </div>
            </div>
          </div>

          <div className="mt-8 rounded-xl border border-blue-200 bg-blue-50 p-5">
            <h3 className="font-bold text-blue-800">💡 Did You Know?</h3>
            <p className="mt-2 text-sm text-slate-700">
              PAYE is only charged after Jamaica&apos;s annual tax-free
              threshold. NIS contributions are capped annually, while NHT and
              Education Tax are generally calculated as a percentage of your
              earnings.
            </p>
          </div>
        </>
      )}
      
      
      <ToolDisclaimer>
  This calculator provides an estimate only. Payroll deductions may vary based
  on official tax updates, pension, benefits, exemptions, and employer payroll
  settings.
</ToolDisclaimer>
    </CalculatorShell>
  );
}

export default SalaryCalculator;